baseURL = 'http://manuel.proyectosdwa.es/'
languageCode = 'es-ES'
title = 'Módulo de backend'
theme =['docsy']




# Para poder cargar emogin https://www.webfx.com/tools/emoji-cheat-sheet/
enableEmoji = true

# Para crear gráficos direccionales
[params.markmap]
    enable = true

#Parámetros para que trabaje mermaid
 [params.mermaid]
enable = true



#Evitando que se despliegue el dos menús a la vez en la ventana izquierda
#Evitando que se despliegue el dos menús a la vez en la ventana izquierda

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false
#  ui.sidebar_menu_compact = true

